#!/bin/bash
# Comprehensive setup verification script for Officemate Backend# This script verifies that all containerization and deployment components are properly configured
# Don't exit on error - we want to collect all issuesset +e
# Colors for outputGREEN='\033[0;32m'YELLOW='\033[1;33m'RED='\033[0;31m'BLUE='\033[0;34m'NC='\033[0m' # No Color
echo -e "${BLUE}=========================================="echo "Officemate Backend Setup Verification"echo -e "==========================================${NC}"echo ""
# Track verification resultsPASSED=0FAILED=0WARNINGS=0
# Function to print successprint_success() { echo -e "${GREEN}✓ $1${NC}" ((PASSED++))}
# Function to print failureprint_failure() { echo -e "${RED}✗ $1${NC}" ((FAILED++))}
# Function to print warningprint_warning() { echo -e "${YELLOW} $1${NC}" ((WARNINGS++))}
# Function to print infoprint_info() { echo -e "${BLUE} $1${NC}"}
echo "1. Checking Docker Installation..."echo "-----------------------------------"if command -v docker &> /dev/null; then DOCKER_VERSION=$(docker --version) print_success "Docker is installed: $DOCKER_VERSION" if docker info > /dev/null 2>&1; then print_success "Docker daemon is running" else print_failure "Docker daemon is not running" fielse print_failure "Docker is not installed"fiecho ""
echo "2. Checking Docker Compose..."echo "-----------------------------------"if docker compose version &> /dev/null; then COMPOSE_VERSION=$(docker compose version) print_success "Docker Compose is installed: $COMPOSE_VERSION"else print_failure "Docker Compose is not installed"fiecho ""
echo "3. Verifying Docker Configuration Files..."echo "-----------------------------------"if [ -f "Dockerfile" ]; then print_success "Dockerfile exists"else print_failure "Dockerfile not found"fi
if [ -f "Dockerfile.prod" ]; then print_success "Dockerfile.prod exists"else print_failure "Dockerfile.prod not found"fi
if [ -f "docker-compose.yml" ]; then print_success "docker-compose.yml exists" # Validate docker-compose.yml if docker compose -f docker-compose.yml config --quiet 2>&1; then print_success "docker-compose.yml is valid" else print_failure "docker-compose.yml has syntax errors" fielse print_failure "docker-compose.yml not found"fi
if [ -f "docker-compose.prod.yml" ]; then print_success "docker-compose.prod.yml exists"else print_warning "docker-compose.prod.yml not found (optional)"fi
if [ -f ".dockerignore" ]; then print_success ".dockerignore exists"else print_warning ".dockerignore not found (recommended)"fiecho ""
echo "4. Checking Environment Configuration..."echo "-----------------------------------"if [ -f ".env.example" ]; then print_success ".env.example exists"else print_failure ".env.example not found"fi
if [ -f ".env" ]; then print_success ".env file exists"else print_warning ".env file not found (will use defaults)" print_info "Run 'make setup' to create .env from template"fiecho ""
echo "5. Verifying Application Configuration..."echo "-----------------------------------"if [ -f "src/main/resources/application.yml" ]; then print_success "application.yml exists"else print_failure "application.yml not found"fi
if [ -f "src/main/resources/application-dev.yml" ]; then print_success "application-dev.yml exists"else print_warning "application-dev.yml not found"fi
if [ -f "src/main/resources/application-prod.yml" ]; then print_success "application-prod.yml exists"else print_warning "application-prod.yml not found"fiecho ""
echo "6. Checking Build Configuration..."echo "-----------------------------------"if [ -f "build.gradle.kts" ]; then print_success "build.gradle.kts exists"else print_failure "build.gradle.kts not found"fi
if [ -f "gradlew" ]; then print_success "Gradle wrapper exists" if [ -x "gradlew" ]; then print_success "Gradle wrapper is executable" else print_warning "Gradle wrapper is not executable (run: chmod +x gradlew)" fielse print_failure "Gradle wrapper not found"fiecho ""
echo "7. Verifying Database Migration Scripts..."echo "-----------------------------------"if [ -d "scripts/db/migrations" ]; then print_success "Migration directory exists" MIGRATION_COUNT=$(ls -1 scripts/db/migrations/*.sql 2>/dev/null | wc -l) if [ $MIGRATION_COUNT -gt 0 ]; then print_success "Found $MIGRATION_COUNT migration file(s)" else print_warning "No migration files found" fielse print_failure "Migration directory not found"fi
if [ -f "scripts/db/run-migrations.sh" ]; then print_success "Migration runner script exists" if [ -x "scripts/db/run-migrations.sh" ]; then print_success "Migration runner is executable" else print_warning "Migration runner is not executable" fielse print_failure "Migration runner script not found"fiecho ""
echo "8. Checking Deployment Scripts..."echo "-----------------------------------"SCRIPTS=("deploy-dev.sh" "deploy-staging.sh" "deploy-prod.sh" "init-dynamodb.sh")for script in "${SCRIPTS[@]}"; do if [ -f "scripts/$script" ]; then print_success "$script exists" if [ -x "scripts/$script" ]; then print_success "$script is executable" else print_warning "$script is not executable" fi else print_warning "$script not found" fidoneecho ""
echo "9. Verifying Makefile..."echo "-----------------------------------"if [ -f "Makefile" ]; then print_success "Makefile exists" # Check for essential targets TARGETS=("build" "test" "docker-up" "docker-down" "migrate" "deploy-dev") for target in "${TARGETS[@]}"; do if grep -q "^$target:" Makefile; then print_success "Makefile has '$target' target" else print_warning "Makefile missing '$target' target" fi doneelse print_failure "Makefile not found"fiecho ""
echo "10. Checking Documentation..."echo "-----------------------------------"DOCS=("README.md" "SETUP.md" "DEPLOYMENT.md" "DOCKER_DEPLOYMENT.md" "CONTAINERIZATION_SUMMARY.md")for doc in "${DOCS[@]}"; do if [ -f "$doc" ]; then print_success "$doc exists" else print_warning "$doc not found" fidoneecho ""
echo "11. Testing Docker Compose Services..."echo "-----------------------------------"print_info "Checking if services are defined in docker-compose.yml..."
SERVICES=("postgres" "redis" "mongodb" "localstack" "mailhog" "app")for service in "${SERVICES[@]}"; do if docker compose -f docker-compose.yml config --services 2>/dev/null | grep -q "^$service$"; then print_success "Service '$service' is defined" else if [ "$service" = "app" ]; then print_info "Service '$service' not found (may be in profile)" else print_warning "Service '$service' not found" fi fidoneecho ""
echo "12. Verifying Volume Configuration..."echo "-----------------------------------"VOLUMES=("postgres_data" "redis_data" "mongodb_data" "localstack_data" "app_logs")for volume in "${VOLUMES[@]}"; do if docker compose -f docker-compose.yml config --volumes 2>/dev/null | grep -q "^$volume$"; then print_success "Volume '$volume' is defined" else print_warning "Volume '$volume' not found" fidoneecho ""
echo "13. Checking Network Configuration..."echo "-----------------------------------"if docker compose -f docker-compose.yml config --quiet 2>&1; then if docker compose -f docker-compose.yml config 2>/dev/null | grep -q "networks:"; then print_success "Network configuration is defined" else print_warning "No custom network defined (using default)" fifiecho ""
echo "14. Verifying Health Check Configuration..."echo "-----------------------------------"print_info "Checking if health checks are configured..."if grep -q "healthcheck:" docker-compose.yml; then print_success "Health checks are configured"else print_warning "No health checks found in docker-compose.yml"fiecho ""
echo "15. Summary..."echo "-----------------------------------"echo -e "${GREEN}Passed: $PASSED${NC}"echo -e "${YELLOW}Warnings: $WARNINGS${NC}"echo -e "${RED}Failed: $FAILED${NC}"echo ""
if [ $FAILED -eq 0 ]; then echo -e "${GREEN}==========================================" echo "✓ Setup verification completed successfully!" echo -e "==========================================${NC}" echo "" echo "Next steps:" echo " 1. Review any warnings above" echo " 2. Run 'make setup' to initialize environment" echo " 3. Run 'make docker-up' to start services" echo " 4. Run 'make init-db' to initialize database" echo " 5. Run 'make run' or 'make docker-up-full' to start the application" echo "" exit 0else echo -e "${RED}==========================================" echo "✗ Setup verification failed!" echo -e "==========================================${NC}" echo "" echo "Please fix the errors above before proceeding." echo "" exit 1fi
